/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:9cc8e0c6-f7a0-4873-87b4-f4273c8410ab",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_zz5U3TXEd",
    "aws_user_pools_web_client_id": "1lgtrpvu5pelq770g753aasb7b",
    "oauth": {}
};


export default awsmobile;
