AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  backend-lambdas

  Sample SAM Template for backend-lambdas

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        ES_URL: http://topothesiacurator-env.eba-ryyjga2w.eu-central-1.elasticbeanstalk.com/

Resources:
  UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: topothesia-upload
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket:
              Ref: UploadBucket     # This must be the name of an S3 bucket declared in the same template file
            Events: s3:ObjectCreated:*

Outputs:
  UploadBucket:
    Description: "A Bucket to upload documents"
    Value: !Ref UploadBucket
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
